### ISSUE TITLE
Theme/Plugins URL rewrite

### ISSUE THREAD

**Issue by Tevora** [zslabs/roots-plug#1]
Hi Zach,

I was using your plugin earlier with themes that employed the roots theme structure. I was sure that it supported rewrites of theme subfolders and plugins urls. 

e.g. 
/wp-content/themes/theme-name/js => /js
/wp-content/themes/theme-name/img => /img
/wp-content/plugins => /plugins

etc.

Will the plugin still be supporting this?

**Comment by zslabs** [comment]
It will not. At the end of the day, a plugin shouldn't be defining how a WordPress theme is structured (plus it was causing a lot of headaches). Removing this makes Roots Plug more compatible with other theme frameworks. You'll see more "helper functions" added, but nothing that will force something like this was doing in the past. 

And not assuming you were thinking this (but just want to cover all basis for anyone else wondering), reformatting the URL structure of your assets doesn't make a site more secure (or hide the fact that you're using WordPress), it's really just adding a layer of complication to your setup that's not needed. Thanks!
